[package]
name = "twister"
version = "0.1.0"
authors = ["Rob N â˜… <robn@robn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.7", features = ["os-poll", "net"] }
hecs = "0.3"
bimap = "0.6"
